import json
import os
from fastapi import APIRouter
from collections import defaultdict

from app.db.database import SessionLocal
from app.models.transaction import Transaction
from app.models.audit_log import AuditLog
from app.schemas.pydantic_schemas import DashboardSummary
from app.services.cache_service import get_cache_metrics

router = APIRouter(prefix="/dashboard", tags=["dashboard"])


@router.get("/summary", response_model=DashboardSummary)
def get_dashboard_summary():
    db = SessionLocal()
    try:
        all_txns = db.query(Transaction).all()

        total_at_risk = sum(t.amount for t in all_txns)
        total_recovered = sum(t.recovered_amount for t in all_txns)
        exceptions_count = sum(1 for t in all_txns if t.is_exception)

        breakdown = defaultdict(lambda: {"count": 0, "recovered_count": 0, "recovered_amount": 0.0})
        for t in all_txns:
            key = t.root_cause or "undiagnosed"
            breakdown[key]["count"] += 1
            breakdown[key]["recovered_amount"] += t.recovered_amount
            if t.status == "recovered":
                breakdown[key]["recovered_count"] += 1

        recovery_rate = (total_recovered / total_at_risk * 100) if total_at_risk > 0 else 0.0

        return DashboardSummary(
            total_at_risk_amount=round(total_at_risk, 2),
            total_recovered_amount=round(total_recovered, 2),
            recovery_rate_pct=round(recovery_rate, 2),
            total_records=len(all_txns),
            exceptions_count=exceptions_count,
            breakdown_by_root_cause=dict(breakdown),
        )
    finally:
        db.close()


@router.get("/merchants")
def get_merchant_breakdown():
    """Per-merchant view — proves the agent generalizes across D2C, SaaS, and B2B, not hardcoded to one."""
    db = SessionLocal()
    try:
        all_txns = db.query(Transaction).all()
        by_merchant = defaultdict(lambda: {"count": 0, "at_risk_amount": 0.0, "recovered_amount": 0.0})

        for t in all_txns:
            m = by_merchant[t.merchant_id]
            m["count"] += 1
            m["at_risk_amount"] += t.amount
            m["recovered_amount"] += t.recovered_amount

        return dict(by_merchant)
    finally:
        db.close()


@router.get("/llm-cache-metrics")
def llm_cache_metrics():
    """Shows how much caching reduced LLM API calls — a real efficiency metric."""
    return get_cache_metrics()


@router.get("/voice-messages")
def get_voice_messages():
    """Real, playable Hinglish voice messages generated by RAAHI, browsable independent of exceptions."""
    db = SessionLocal()
    try:
        txns = db.query(Transaction).filter(Transaction.voice_message_url.isnot(None)).limit(20).all()
        return [
            {
                "id": t.id, "amount": t.amount, "root_cause": t.root_cause,
                "voice_message_text": t.voice_message_text,
                "voice_message_url": t.voice_message_url,
            }
            for t in txns
        ]
    finally:
        db.close()


@router.get("/channel-distribution")
def get_channel_distribution():
    """Shows how RAAHI's Decision Agent actually differentiates channel selection across the batch."""
    db = SessionLocal()
    try:
        txns = db.query(Transaction).filter(Transaction.channel.isnot(None)).all()
        counts = {}
        for t in txns:
            counts[t.channel] = counts.get(t.channel, 0) + 1
        return counts
    finally:
        db.close()


@router.get("/outcome-source-breakdown")
def get_outcome_source_breakdown():
    """Honest breakdown: real webhook-verified outcomes vs. modeled vs. ML-training-only simulation."""
    db = SessionLocal()
    try:
        txns = db.query(Transaction).all()
        counts = {}
        for t in txns:
            src = t.outcome_source or "unset"
            counts[src] = counts.get(src, 0) + 1
        return counts
    finally:
        db.close()


@router.get("/ml-model-metrics")
def get_ml_model_metrics():
    """Real, honestly-reported confidence model performance from the last training run."""
    path = "app/ml/model_artifacts/metrics.json"
    if not os.path.exists(path):
        return {"message": "Model not yet trained"}
    with open(path) as f:
        return json.load(f)


@router.get("/comparison")
def get_comparison():
    """RAAHI (intelligent) vs. naive baseline — same starting data, different decision logic."""
    db = SessionLocal()
    try:
        result = {}
        for suffix, label in [("_raahi", "raahi"), ("_naive", "naive")]:
            txns = db.query(Transaction).filter(Transaction.merchant_id.like(f"%{suffix}")).all()
            exceptions = sum(1 for t in txns if t.is_exception)
            result[label] = {
                "total_records": len(txns),
                "exceptions_caught": exceptions,
                "total_at_risk": sum(t.amount for t in txns),
            }
        return result
    finally:
        db.close()


@router.get("/recent-events")
def get_recent_events(limit: int = 15):
    """Live activity feed — most recent audit trail entries across all agents/stages."""
    db = SessionLocal()
    try:
        logs = db.query(AuditLog).order_by(AuditLog.timestamp.desc()).limit(limit).all()
        return [{"stage": l.stage, "summary": l.summary, "timestamp": l.timestamp.isoformat()} for l in logs]
    finally:
        db.close()

@router.get("/retry-timing-model")
def get_retry_timing_model():
    """Shows the learned optimal retry-timing recommendations per root cause, vs. baseline."""
    path = "app/ml/model_artifacts/retry_timing_recommendations.json"
    if not os.path.exists(path):
        return {"message": "Timing model not yet trained"}
    with open(path) as f:
        return json.load(f)